import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url))); const catalogPath = path.join(root, 'data', 'catalog.json');
const args = process.argv.slice(2); const getArg = name => args[args.indexOf(name) + 1]; const sourceArg = getArg('--source'); const fileArg = getArg('--file');
const sourceNames = { ablesci:'ablesci', wos:'ablesci', scopus:'scopus', scimago:'scimago', core:'core' }; const source = sourceNames[sourceArg?.toLowerCase()];
if (!source || !fileArg) { console.error('Usage: npm run import -- --source <ablesci|scopus|scimago|core> --file <path-to-csv-json-xlsx>'); process.exit(1); }
const clean = value => String(value ?? '').trim(); const key = value => clean(value).toLowerCase().replace(/[^a-z0-9]+/g, '');
function pick(row, names) { const found = Object.entries(row).find(([k]) => names.some(name => key(k) === key(name))); return found ? clean(found[1]) : ''; }
const splitList = value => clean(value).split(/[;,|]/).map(v => v.trim()).filter(Boolean);
const numberOrNull = value => { const n = Number(String(value).replace(',', '.').replace(/[^0-9.-]/g, '')); return Number.isFinite(n) ? n : null; };
function csvRows(text) { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean); if (!lines.length) return []; const parse = line => { const out=[]; let cell='', quoted=false; for (let i=0;i<line.length;i++) { const c=line[i]; if (c==='"' && line[i+1]==='"') { cell+='"'; i++; } else if (c==='"') quoted=!quoted; else if (c===',' && !quoted) { out.push(cell); cell=''; } else cell+=c; } out.push(cell); return out; }; const headers=parse(lines[0]); return lines.slice(1).map(line => Object.fromEntries(parse(line).map((v,i) => [headers[i] || `column_${i}`, v]))); }
async function readRows(file) { const ext=path.extname(file).toLowerCase(); if (ext==='.json') return JSON.parse(await readFile(file,'utf8')); if (ext==='.csv' || ext==='.tsv') return csvRows((await readFile(file,'utf8')).replaceAll('\t',',')); if (ext==='.xlsx' || ext==='.xls') { try { const { read, utils }=await import('xlsx'); const workbook=read(await readFile(file)); return utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{defval:''}); } catch { throw new Error('XLSX import needs optional package: npm install xlsx'); } } throw new Error(`Unsupported file type: ${ext}`); }
function toRecord(row, index) { const title=pick(row,['title','source title','journal title','conference','conference name','name']) || `Imported ${source} ${index+1}`; const issn=pick(row,['issn','print issn']); const eissn=pick(row,['eissn','electronic issn','e-issn']); const base={ id:`${source}-${(issn || title).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}`, title, type:source==='core' || /conference|proceedings/i.test(title) ? 'conference':'journal', publisher:pick(row,['publisher']), issn, eissn, aliases:splitList(pick(row,['alias','aliases','acronym'])), subjects:splitList(pick(row,['subject','subject area','asjc','field'])), deadlines:splitList(pick(row,['deadline','submission deadline','paper deadline','abstract deadline','due date'])), sources:[source], sourceUpdated:pick(row,['year','data year','updated','update date']) || new Date().getFullYear().toString() }; if(source==='ablesci') base.wos={ impactFactor:numberOrNull(pick(row,['impact factor','if','影响因子'])), quartile:pick(row,['quartile','jcr quartile','分区']), category:pick(row,['category','subject category']) }; if(source==='scopus') base.scopus={ citeScore:numberOrNull(pick(row,['citescore','cite score'])), snip:numberOrNull(pick(row,['snip'])), sjr:numberOrNull(pick(row,['sjr'])), percentile:pick(row,['percentile','highest percentile']), quartile:pick(row,['quartile','citescore quartile']) }; if(source==='scimago') base.scimago={ sjr:numberOrNull(pick(row,['sjr','sjr 2024','sjr 2023'])), hIndex:numberOrNull(pick(row,['h index','h-index','hindex'])), quartile:pick(row,['quartile','best quartile']), country:pick(row,['country','country/territory']), category:pick(row,['category','categories']) }; if(source==='core') base.core={ rank:pick(row,['rank','core rank','ranking','tier']), year:pick(row,['year','ranking year']) || new Date().getFullYear().toString(), field:pick(row,['field','discipline']) }; return base; }
const rows=await readRows(path.resolve(fileArg)); const incoming=rows.map(toRecord); const current=JSON.parse(await readFile(catalogPath,'utf8')); const byKey=new Map(current.map(item=>[item.issn || item.title.toLowerCase(),item]));
for(const record of incoming) { const identity=record.issn || record.title.toLowerCase(); const old=byKey.get(identity); if(!old) byKey.set(identity,record); else byKey.set(identity,{...old,...record,sources:[...new Set([...(old.sources||[]),source])],wos:{...old.wos,...record.wos},scopus:{...old.scopus,...record.scopus},scimago:{...old.scimago,...record.scimago},core:{...old.core,...record.core}}); }
await writeFile(catalogPath, JSON.stringify([...byKey.values()],null,2)+'\n'); console.log(`Imported ${incoming.length} rows from ${source}. Catalog now has ${byKey.size} records.`);
